version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: jms_mysql
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: jumpserver
    command: --character-set-server=utf8
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - jumpserver

  redis:
    image: redis:alpine
    container_name: jms_redis
    restart: always
    tty: true
    volumes:
      - redis-data:/data
    networks:
      - jumpserver

  core:
    build:
      context: .
      dockerfile: core/Dockerfile
      args:
        Version: ${Version}
    image: jms_core:${Version}
    container_name: jms_core
    hostname: jms_core
    restart: always
    tty: true
    environment:
      SECRET_KEY: $SECRET_KEY
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      DB_ENGINE: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: $MYSQL_ROOT_PASSWORD
      DB_NAME: jumpserver
      REDIS_HOST: redis
    depends_on:
      - mysql
      - redis
    volumes:
      - static:/opt/jumpserver/data/static
      - media:/opt/jumpserver/data/media
      - logs:/opt/jumpserver/logs
    networks:
      - jumpserver

  koko:
    build:
      context: .
      dockerfile: koko/Dockerfile
      args:
        Version: ${Version}
        GOPROXY: https://goproxy.io
    image: jms_koko:${Version}
    container_name: jms_koko
    restart: always
    tty: true
    environment:
      CORE_HOST: http://core:8080
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
    depends_on:
      - core
      - mysql
      - redis
    volumes:
      - keys-data:/opt/koko/data/keys
    ports:
      - 2222:2222
    networks:
      - jumpserver

  guacamole:
    build:
      context: .
      dockerfile: guacamole/Dockerfile
      args:
        Version: ${Version}
    image: jms_guacamole:${Version}
    container_name: jms_guacamole
    restart: always
    tty: true
    environment:
      JUMPSERVER_SERVER: http://core:8080
      BOOTSTRAP_TOKEN: $BOOTSTRAP_TOKEN
      JUMPSERVER_KEY_DIR: /config/guacamole/keys
      GUACAMOLE_HOME: /config/guacamole
    depends_on:
      - core
      - mysql
      - redis
    volumes:
      - gua-key:/config/guacamole/keys
    networks:
      - jumpserver

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
      args:
        Version: ${Version}
    image: jms_nginx:${Version}
    container_name: jms_nginx
    restart: always
    tty: true
    depends_on:
      - core
      - koko
      - mysql
      - redis
    volumes:
      - static:/opt/jumpserver/data/static
      - media:/opt/jumpserver/data/media
    ports:
      - 80:80
    networks:
      - jumpserver

volumes:
  static:
  media:
  logs:
  db-data:
  redis-data:
  keys-data:
  gua-key:

networks:
  jumpserver:
